services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    command: npm run start

  moleculer-services:
    build:
      context: .
      dockerfile: Dockerfile.moleculer
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    command: npx ts-node /app/moleculer.config.ts
