services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/app
    command: npm run dev

  moleculer-services:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: npx ts-node /app/moleculer.config.ts
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/app
