### POST request to add todo
POST http://localhost:3000/api/addTodos
Content-Type: application/json

{ 
  "text": "I Love Anime!"
}

### GET request to List all todos
GET http://localhost:3000/api/listTodos
Content-Type: application/json

### PUT to toggle todo
PUT http://localhost:3000/api/toggleTodo
Content-Type: application/json

{ 
  "id": "6713a6f9f2676e2cf6d39f82"
}

### DELETE to delete todo
DELETE http://localhost:3000/api/removedTodos
Content-Type: application/json

{ 
  "id": "6713a6f9f2676e2cf6d39f82"
}