### POST request to add todo
POST http://localhost:3000/api/addTodos
Content-Type: application/json

{ 
  "text": "I Love Anime!"
}

### GET request to List all todos
GET http://localhost:3000/api/listTodos
Content-Type: application/json

### PUT to toggle todo
PUT http://localhost:3000/api/toggleTodo?id=1728558765712
Content-Type: application/json


### DELETE to delete todo
DELETE http://localhost:3000/api/removedTodos?id=1728558765712
Content-Type: application/json